name: TMM4128_model
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3
  - pytorch==1.12.1
  - torchaudio==0.12.1
  - torchvision==0.13.1
  - conda-libmamba-solver
  - scipy
  - matplotlib
  - imgaug
  - gdal
  - rasterio
  - geopandas
  - ipykernel
